---
database:
  host: localhost
  name: "{{ site.domain.replace('.', '_') }}"
  sub_name: "{{ site.domain.replace('.', '_') }}_{{ site.subdomain | default('sub') }}"
  password: "{{ lookup('pipe', playbook_dir + '/get_password.py ' + site.domain + ' Database') }}"
  username: "{{ lookup('pipe', playbook_dir + '/get_username.py ' + site.subdomain|default('') + ' ' + site.domain) }}"
  type: "{{ site.database_type | default('mysql') }}"
